Fix clusterSelector default value
stolostron/policy-generator-plugin pull request #98
Opened 2023-02-15 23:15 UTC by serngawy

2023-02-15 23:17 UTC, serngawy commented
/assign @dhaiducek

2023-02-16 01:47 UTC, dhaiducek requested changes
Thanks for the bug fix and doc update! I have some minor wording suggestions.

2023-02-16 01:47 UTC, dhaiducek commented on docs/policygenerator-reference.yaml
>      labelSelector: {}
```suggestion
    # To specify a placement, specify key:value pair cluster label selectors or the full LabelSelector for the desired cluster
    # label selectors. (See placementPath to specify an existing file instead.)
    # For example, to specify a placement using matchExpressions:
    #   labelSelector:
    #     matchExpressions:
    #       - key: provider
    #         operator: NotIn
    #         values:
    #          - "cloud"
    labelSelector: {}
```

2023-02-16 01:47 UTC, dhaiducek commented on docs/policygenerator-reference.yaml
>      clusterSelector: {}
```suggestion
    # To specify a placement rule, specify key:value pair cluster selectors or the full LabelSelector for the desired cluster
    # selectors. (See placementRulePath to specify an existing file instead.)
    # For example, to specify a placement rule using matchExpressions:
    #   clusterSelector:
    #     matchExpressions:
    #       - key: provider
    #         operator: NotIn
    #         values:
    #          - "cloud"
```

2023-02-16 14:43 UTC, serngawy commented on docs/policygenerator-reference.yaml
>      labelSelector: {}
done

2023-02-16 14:43 UTC, serngawy commented on docs/policygenerator-reference.yaml
>      clusterSelector: {}
okay, done

2023-02-16 16:09 UTC, mprahl approved these changes
Thanks!

2023-02-16 16:12 UTC, merged